# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Probably wrong
email: eugenusb@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ideas, thoughts, code, questions and occasionally answers on Machine Learning, Algorithms and Math.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: eugenus_b
github_username: eugenusb
linkedin_username: eugenio-borghini-841b301ba
author: Eugenio Borghini

google_analytics: UA-211612259-1

# Build settings
remote_theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

markdown: kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"

sass:
  sass_dir: _sass
  style: compressed